using System;
using System.IO;
using System.Reflection;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace DecalMini.Editor
{
    /// <summary>
    /// 自动化 HLSL 生成器：确保 C# 与 Shader 数据源完全统一
    /// </summary>
    public class HLSLGeneratorMini : AssetPostprocessor
    {
        // [REMOVED] Hardcoded SAVE_PATH constant

        // 当资产导入完成时触发检测
        private static void OnPostprocessAllAssets(
            string[] importedAssets,
            string[] deletedAssets,
            string[] movedAssets,
            string[] movedFromAssetPaths
        )
        {
            foreach (string str in importedAssets)
            {
                if (str.EndsWith("DecalDataMini.cs"))
                {
                    Generate();
                    break;
                }
            }
        }

        [MenuItem("Tools/Decal System/Force Generate HLSL")]
        public static void Generate()
        {
            // 0. 获取配置路径
            string savePath =
                DecalSystemSettings.Instance != null
                    ? DecalSystemSettings.Instance.generatedHLSLPath
                    : "Assets/Modules/DecalSystem/Shaders/DecalDataMini.generated.hlsl";

            // 1. 获取 C# 源码路径
            string[] guids = AssetDatabase.FindAssets("DecalDataMini t:Script");
            if (guids.Length == 0)
                return;
            string csPath = AssetDatabase.GUIDToAssetPath(guids[0]);
            string source = File.ReadAllText(csPath);

            StringBuilder sb = new StringBuilder();
            sb.AppendLine("// ============================================================");
            sb.AppendLine("// AUTO GENERATED BY HLSLGeneratorMini.cs - DO NOT MODIFY");
            sb.AppendLine("// Date: " + DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"));
            sb.AppendLine("// ============================================================");
            sb.AppendLine();

            // 2. 使用正则提取带有 [HLSLStruct] 的结构体内容
            var structMatch = System.Text.RegularExpressions.Regex.Match(
                source,
                @"\[HLSLStruct\].*?struct\s+(\w+)\s*\{(.*?)\}",
                System.Text.RegularExpressions.RegexOptions.Singleline
            );
            if (structMatch.Success)
            {
                string structName = structMatch.Groups[1].Value;
                string body = structMatch.Groups[2].Value;

                sb.AppendLine($"struct {structName}");
                sb.AppendLine("{");

                // 3. 提取所有 public 字段
                var fieldMatches = System.Text.RegularExpressions.Regex.Matches(
                    body,
                    @"public\s+(\w+)\s+([\w,\s]+);"
                );
                foreach (System.Text.RegularExpressions.Match m in fieldMatches)
                {
                    string type = m.Groups[1].Value;
                    string[] names = m.Groups[2].Value.Split(',');

                    foreach (string name in names)
                    {
                        string cleanName = name.Trim();
                        if (string.IsNullOrEmpty(cleanName))
                            continue;
                        sb.AppendLine($"    {MapType(type)} {cleanName};");
                    }
                }

                sb.AppendLine("};");
            }

            string fullPath = savePath;

            // 确保目录存在
            string dir = Path.GetDirectoryName(fullPath);
            if (!Directory.Exists(dir))
                Directory.CreateDirectory(dir);

            File.WriteAllText(fullPath, sb.ToString());
            AssetDatabase.ImportAsset(savePath);

            Debug.Log(
                $"<color=#7C8CFF><b>[Decal Mini]</b></color> HLSL bridge generated from SOURCE at: <color=#9CDCFE>{savePath}</color>"
            );
        }

        private static string MapType(string t)
        {
            return t switch
            {
                "Vector4" => "float4",
                "Vector3" => "float3",
                "Vector2" => "float2",
                "float" => "float",
                "int" => "int",
                "uint" => "uint",
                "Matrix4x4" => "float4x4",
                _ => "float4",
            };
        }
    }
}
