// ============================================================
// AUTO GENERATED BY HLSLGeneratorMini.cs - DO NOT MODIFY
// Deterministic output. Regenerate only when DecalDataMini changes.
// ============================================================

struct DecalDataMini
{
    float4 wtd0;
    float4 wtd1;
    float4 wtd2;
    float4 wtd3;
    float4 dtw0;
    float4 dtw1;
    float4 dtw2;
    float4 dtw3;
    float4 color;
    float4 uvScaleOffset;
    float4 fadeParams;
    float4 animParams;
    float4 animParams2;
    float4 auraColor2;
    float4 auraColor3;
    float4 auraColor4;
    float4 auraRotSpeeds;
    float4 auraPulseParams;
    float4 auraScaleParams;
    float4 auraMiscParams;
};
